# Generated by Django 4.0.2 on 2022-02-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_perevaladded_perevalareas_perevalimages_delete_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerevalAdded',
            new_name='Added',
        ),
        migrations.RenameModel(
            old_name='PerevalAreas',
            new_name='Areas',
        ),
        migrations.RenameModel(
            old_name='PerevalImages',
            new_name='Images',
        ),
        migrations.AlterModelTable(
            name='added',
            table=None,
        ),
        migrations.AlterModelTable(
            name='areas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='images',
            table=None,
        ),
    ]
