# Generated by Django 4.0.2 on 2022-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_rename_perevaladded_added_rename_perevalareas_areas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Added',
            new_name='PerevalAdded',
        ),
        migrations.RenameModel(
            old_name='Areas',
            new_name='PerevalAreas',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='PerevalImages',
        ),
        migrations.AlterModelOptions(
            name='perevaladded',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perevalareas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perevalimages',
            options={},
        ),
        migrations.AlterModelTable(
            name='perevaladded',
            table='pereval_added',
        ),
        migrations.AlterModelTable(
            name='perevalareas',
            table='pereval_areas',
        ),
        migrations.AlterModelTable(
            name='perevalimages',
            table='pereval_images',
        ),
    ]
