# Generated by Django 4.0.2 on 2022-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0008_testclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='js',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
