# Generated by Django 4.0.2 on 2022-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0010_rename_js_testclass_images_remove_testclass_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True)),
                ('images', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В обработке'), ('resolved', 'Завершен'), ('accepted', 'Принят'), ('rejected', 'Отменен')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.DeleteModel(
            name='PerevalAdded',
        ),
        migrations.DeleteModel(
            name='PerevalAreas',
        ),
        migrations.DeleteModel(
            name='PerevalImages',
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
