# Generated by Django 4.0.2 on 2022-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('images', models.JSONField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
