# Generated by Django 4.0.2 on 2022-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_rename_added_perevaladded_rename_areas_perevalareas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='status',
            field=models.TextField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='images',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='raw_data',
            field=models.JSONField(blank=True),
        ),
    ]
