# Generated by Django 4.0.2 on 2022-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_perevaladded_status_alter_perevaladded_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('number', models.IntegerField(blank=True)),
            ],
        ),
    ]
